install.packages("Seurat")
install.packages("patchwork")
install.packages("SeuratData")
library(Seurat)
library(SeuratData)
InstallData("pbmc3k")
data("pbmc3k")
pbmc <- pbmc3k
install.packages("SeuratData")
library(SeuratData)
install.packages("remotes")
remotes::install_github("satijalab/seurat-data")
library(SeuratData)
InstallData("pbmc3k")